[build]
  base = "fertilizer-shop-ui"
  command = "npm run build"
  publish = "fertilizer-shop-ui/dist/fertilizer-shop-ui/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
